language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/

matrix:
  fast_finish: true
  include:
    - name: "PHPCS"
      php: 7.3
      env:
        - CS_CHECK=true
    - name: "Build Phar"
      php: 7.1
      env:
        - BUILD_PHAR=true
    - name: "Tests PHP 7.1 Lowest Dependencies"
      php: 7.1
      env:
        - DEPS=lowest
    - name: "Tests PHP 7.1 PHPUnit Dev Version"
      php: 7.1
      env:
        - PHPUNIT_DEV=true
    - name: "Tests PHP 7.1"
      php: 7.1
    - name: "Tests PHP 7.2 Lowest Dependencies"
      php: 7.2
      env:
        - DEPS=lowest
    - name: "Tests PHP 7.2 PHPUnit Dev Version"
      php: 7.2
      env:
        - PHPUNIT_DEV=true
    - name: "Tests PHP 7.2"
      php: 7.2
    - php: 7.3
      name: "Tests PHP 7.3 Lowest Dependencies"
      env:
        - DEPS=lowest
    - name: "Tests PHP 7.3 PHPUnit Dev Version"
      php: 7.3
      env:
        - PHPUNIT_DEV=true
    - name: "Tests PHP 7.3"
      php: 7.3
    - name: "Tests PHP Nightly"
      php: nightly
  allow_failures:
    - php: nightly

install:
  - if [[ $CS_CHECK == 'true' ]]; then phpenv config-rm xdebug.ini || return 0; fi;
  - if [[ $PHPUNIT_DEV == 'true' ]]; then composer require --no-update phpunit/phpunit=*@dev; fi;
  - if [[ $DEPS == 'lowest' ]]; then COMPOSER_ARGS='--prefer-lowest --prefer-stable'; fi; composer update --no-interaction --prefer-dist $COMPOSER_ARGS;
  - if [[ $BUILD_PHAR == 'true' ]]; then wget https://github.com/humbug/box/releases/download/3.7.0/box.phar; fi;
  - composer install

script:
  - if [[ $CS_CHECK == 'true' ]]; then vendor/bin/phpcs --ignore=*/test/fixtures/*,bootstrap.php --standard=PSR12 ./src/ ./test/; fi;
  - if [[ $CS_CHECK != 'true' ]]; then vendor/bin/phpunit $COVERAGE_ARGS; fi;

before_deploy:
  - if [[ $BUILD_PHAR == 'true' ]]; then php box.phar compile; fi;

deploy:
  provider: releases
  api_key:
    secure: OER6C7dNaVOIhl2wEA2i2Qe4T6BcXuM/cP0vOoz4578X0LRipYudWMXnLXYmMmjzraMBJ2W3cQx830mQK0TBVU/m0hp5bpTcfGsOBX7+sLi6MY/ncDa4kXV2x8qZOmQLRtk3smAgMyh5hUp7qlmpDRJJ9F1xCYFNqpotK8N3Rfk=
  file: bin/paratest.phar
  skip_cleanup: true
  on:
    condition: $BUILD_PHAR == 'true'
    repo: paratestphp/paratest
    tags: true

notifications:
  email: false
